### ISSUE TITLE
Ensure Maven reproducibility

### ISSUE THREAD

**Issue by felipeqq2** [yellowisk/TechMaps-Back-v2#2]
At the very least, specify `org.jetbrains.annotations`:

https://github.com/yellowisk/TechMaps-Back-v2/blob/main/pom.xml#L54-L59

**Comment by yellowisk** [comment]
I don't even remember why this dependency is in project, honestly... I think it was added automatically, so I don't mind removing it altogether. Most annotations this project will require are going to be from jakarta or springframework.

**Comment by felipeqq2** [comment]
Beleza, eu vou dar uma revisada nas dependências entre hoje e sábado, e aí resolvo isso também.

**Comment by yellowisk** [comment]
> Beleza, eu vou dar uma revisada nas dependências entre hoje e sábado, e aí resolvo isso também.
> […](#)
> On 6 June 2024 10:46:30 GMT-03:00, Heitor Almeida ***@***.***> wrote: I don't even remember why this dependency is in project, honestly... I think it was added automatically, so I don't mind removing it altogether. Most annotations this project will require are going to be from jakarta or springframework.

Beleza, foi muito boa essa sua observação sobre a anotação do JetBrains. Valeu, Felipe!
